# Generated by Django 4.2.4 on 2023-08-21 15:08

import Posts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_city', models.CharField(max_length=50)),
                ('post_street', models.CharField(max_length=50)),
                ('post_apartment_number', models.CharField(max_length=50)),
                ('post_apartment_price', models.CharField(max_length=10)),
                ('post_rent_start', models.DateField()),
                ('post_rent_end', models.DateField()),
                ('proof_image', models.ImageField(upload_to=Posts.models.generate_unique_filename)),
                ('driving_license', models.ImageField(upload_to=Posts.models.generate_unique_filename)),
                ('post_description', models.CharField(max_length=2000)),
                ('proof_image_confirmed', models.BooleanField(default=False)),
                ('apartment_pic_1', models.ImageField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename)),
                ('post_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Users.users')),
            ],
        ),
    ]
