# Generated by Django 4.2.4 on 2024-06-03 11:03

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_user_id', models.IntegerField()),
                ('post_city', models.CharField(max_length=50)),
                ('post_street', models.CharField(max_length=50)),
                ('post_building_number', models.CharField(max_length=50)),
                ('post_apartment_number', models.CharField(max_length=50)),
                ('post_apartment_price', models.CharField(max_length=10)),
                ('post_rent_start', models.DateField()),
                ('post_rent_end', models.DateField()),
                ('post_review', models.CharField(max_length=5000)),
                ('post_rating', models.CharField(default='0', max_length=3)),
                ('confirmation_status', models.CharField(default='0', max_length=1)),
                ('rent_agreement', models.FileField(upload_to=Posts.models.upload_to_rent_docs)),
                ('driving_license', models.FileField(upload_to=Posts.models.upload_to_rent_docs)),
                ('apartment_pic_1', models.ImageField(blank=True, null=True, upload_to=Posts.models.upload_to_apartment_pics)),
                ('apartment_pic_2', models.ImageField(blank=True, null=True, upload_to=Posts.models.upload_to_apartment_pics)),
                ('apartment_pic_3', models.ImageField(blank=True, null=True, upload_to=Posts.models.upload_to_apartment_pics)),
                ('apartment_pic_4', models.ImageField(blank=True, null=True, upload_to=Posts.models.upload_to_apartment_pics)),
                ('user_addition_comments', models.CharField(blank=True, default='No comment', max_length=2000, null=True)),
            ],
        ),
    ]
