# Generated by Django 4.2.4 on 2023-08-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0004_remove_users_user_password_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_city', models.CharField(max_length=50)),
                ('post_street', models.CharField(max_length=50)),
                ('post_apartment_number', models.CharField(max_length=50)),
                ('post_apartment_price', models.IntegerField()),
                ('post_rent_start', models.DateField()),
                ('post_rent_end', models.DateField()),
                ('proof_image', models.ImageField(upload_to='posts/images/')),
                ('driving_license', models.ImageField(upload_to='posts/images')),
                ('post_description', models.CharField(max_length=2000)),
                ('proof_image_confirmed', models.BooleanField(default=False)),
                ('driving_license_confirmed', models.BooleanField(default=False)),
                ('apartment_pic_1', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('apartment_pic_2', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('apartment_pic_3', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('apartment_pic_4', models.ImageField(blank=True, null=True, upload_to='posts/images')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Users.users')),
            ],
        ),
    ]
