# Generated by Django 4.2.4 on 2023-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='driving_license_confirmed',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_apartment_price',
            field=models.CharField(max_length=10),
        ),
    ]
