# Generated by Django 4.2.4 on 2023-08-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_post_driving_license_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='apartment_pic_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='apartment_pic_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='apartment_pic_4',
        ),
    ]
