# Generated by Django 4.2.4 on 2023-09-11 09:48

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_remove_post_apartment_pic_1_apartmentimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='apartment_images',
        ),
        migrations.AddField(
            model_name='post',
            name='apartment_pic_1',
            field=models.ImageField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.DeleteModel(
            name='ApartmentImage',
        ),
    ]
