# Generated by Django 4.2.4 on 2023-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_rename_post_user_post_post_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
