# Generated by Django 4.2.4 on 2023-09-12 06:59

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_remove_post_apartment_images_post_apartment_pic_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_field',
            field=models.FileField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename),
        ),
    ]
