# Generated by Django 4.2.4 on 2023-08-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_post_apartment_pic_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_1',
            field=models.ImageField(blank=True, null=True, upload_to='Post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='driving_license',
            field=models.ImageField(upload_to='Post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='proof_image',
            field=models.ImageField(upload_to='Post/'),
        ),
    ]
