# Generated by Django 4.2.4 on 2023-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_post_apartment_pic_2_post_apartment_pic_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_building_number',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
