# Generated by Django 4.2.4 on 2023-09-13 10:33

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_alter_post_post_building_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_1',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_2',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_3',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_4',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=Posts.models.generate_unique_filename),
        ),
    ]
