# Generated by Django 4.2.4 on 2023-12-21 10:19

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_alter_post_apartment_pic_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='proof_image_confirmed',
        ),
        migrations.AddField(
            model_name='post',
            name='confirmation_status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_1',
            field=models.ImageField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_2',
            field=models.ImageField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_3',
            field=models.ImageField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='apartment_pic_4',
            field=models.ImageField(blank=True, null=True, upload_to=Posts.models.generate_unique_filename),
        ),
    ]
