# Generated by Django 4.2.4 on 2023-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_remove_post_proof_image_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
