# Generated by Django 4.2.4 on 2023-12-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0013_post_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='proof_image',
            new_name='rent_agreement',
        ),
    ]
