# Generated by Django 4.2.4 on 2024-01-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0014_rename_proof_image_post_rent_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, default='No comment', max_length=2000, null=True),
        ),
    ]
