# Generated by Django 4.2.4 on 2024-01-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0015_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='post_comments',
        ),
    ]
