# Generated by Django 4.2.4 on 2024-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inbox', '0002_userinbox_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinbox',
            name='headline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
