# Generated by Django 4.2.4 on 2024-03-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inbox', '0003_userinbox_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbox',
            name='headline',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
