# Generated by Django 4.2.4 on 2023-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=3)),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('user_phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
