# Generated by Django 4.2.4 on 2023-08-30 11:41

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Users.models.generate_unique_filename),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_full_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
