# Generated by Django 4.2.4 on 2023-08-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password_2',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
