# Generated by Django 4.2.4 on 2023-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_user_profile_pic_alter_users_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
