# Generated by Django 4.2.4 on 2023-08-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_users_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_password_2',
        ),
    ]
