# Generated by Django 4.2.4 on 2023-12-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_message_1', models.CharField(default='', max_length=200)),
                ('user_message_2', models.CharField(default='', max_length=200)),
                ('user_message_3', models.CharField(default='', max_length=200)),
                ('user_message_4', models.CharField(default='', max_length=200)),
                ('user_message_5', models.CharField(default='', max_length=200)),
                ('user_message_6', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
