name: Cleanup Verification Codes

on:
  schedule:
    # Set to runevery day at 00:00 UTC
    - cron: '* * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install mysql-connector-python
        run: |
          pip install mysql-connector-python==8.1.0
      - name: Run Cleanup Script
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER}}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST}}
        run: 
          python .github/workflows/delete_old_verification_codes.py
